# (PART) Grundrezepte

# Fischsoßenessig

## Beschreibung

Fischsoßenessig wird besonders in der vietnamnesischen Küche verwendet, um die Speisen zu verfeinern. Passt besonders gut als Soße zu Reis oder zu Salat. 

## Zutatenliste

Zutat | Menge 
---|---:
Wasser | 2 Tassen
Zucker | 1 Tasse
Fischsoße | 1 Tasse
Weinbrandt- oder Apfelessig (5 %) | 1/2 Tasse


## Zubereitung
Alle Zutaten mixen.


# Eingelegte Karottenstreifen

## TO-DO Liste

- Bild von Gericht einfügen
-  ~~Zutaten bestimmen~~
- ~~Zubereitungstext ausformulieren~~



## Beschreibung


## Zutatenliste

Zutat | Menge 
---|---:
Karotten | -
Salz | etwas
Zucker | -
Essig 5 % | -
Wasser | -


## Zubereitung

Die Karotten schälen und in Streifen reiben. Danach wird etwas Salz auf die geriebenen Karottenstreifen gestreut. Nach einer kurzen Einwirkzeit wird das Wasser aus den Karottenstreifen mit der Hand ausgepresst. Mittels Essig und Zucker werden die Karotten abgeschmeckt. Zur längeren Aufbewahrung werden die Streifen in Gläser eingelegt. Alles wird mit Wasser aufgefüllt, sodass die Karotten komplett mit Wasser bedeckt sind. 


# Ziehnudeln 拉面

## TO-DO

# Vietnamnesisch geröstete Zwiebeln

## TO-DO


# Getrocknete Eiernudeln

## TO-DO

- Text besser ausformulieren
- Bild einfügen

## Beschreibung

Eiernudeln für 100 g Mehl.

## Zutatenliste

Zutat | Menge 
---|---:
Hartweizengrieß | 50 g
Weizenmehl | 50 g
Olivenöl | etwas
Wasser | 2 Esslöffel

## Zubereitung
1. Zutaten vermischen bis der Teig die richtige Konsistenz hat
2. Ca. 1 Stunde im Kühlschrank kühlen
3. Nudeln formen (Nudelmaschine)
4. Zum Trocknen aufhängen.

# Suppenpaste

## Beschreibung
Aus Netflix Serie... Paste zum schnellen aufsetzen von Nudelsuppen.

## Zutatenliste

## Zubereitung