name: Deploy Bookdown Site to GitHub Pages (docs folder)

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Pandoc
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      # Step 3: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("bookdown")'

      # Step 5: Build the Bookdown site with output to 'docs' folder
      - name: Build Bookdown site
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", output_dir = "docs")'

      # Step 6: List files in the 'docs' directory for debugging
      - name: List files in docs directory (for debugging)
        run: |
          ls -la docs  # Verify that the docs folder has been created and populated

      # Step 7: Setup GitHub Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 8: Upload the 'docs' d
