name: Deploy Bookdown Site to GitHub Pages using Docker

on:
  push:
    branches:
      - main  # Trigger on commits to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Pull Docker image with Bookdown installed
      - name: Pull Bookdown Docker Image
        run: |
          docker pull dockerscripts/bookdown:latest

      # Step 3: Run Bookdown build inside the Docker container
      - name: Build Bookdown site with Docker
        run: |
          docker run --rm -v $(pwd):/usr/src/app -w /usr/src/app dockerscripts/bookdown:latest Rscript -e 'bookdown::render_book("index.Rmd", output_dir = "docs")'

      # Step 4: List files in docs directory for debugging
      - name: List files in docs directory (for debugging)
        run: |
          ls -la docs

      # Step 5: Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 6: Upload the docs folder to GitHub Pages
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
